package com.ubosque.edu.co.progll.modelo;
// Generated 12/11/2018 11:20:32 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asunto generated by hbm2java
 */
@Entity
@Table(name = "asunto")
public class Asunto implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set<Documento> documentosForUsuarioId = new HashSet<Documento>(0);
	private Set<Documento> documentosForAsuntoId = new HashSet<Documento>(0);

	public Asunto() {
	}

	public Asunto(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Asunto(int id, String nombre, Set<Documento> documentosForUsuarioId, Set<Documento> documentosForAsuntoId) {
		this.id = id;
		this.nombre = nombre;
		this.documentosForUsuarioId = documentosForUsuarioId;
		this.documentosForAsuntoId = documentosForAsuntoId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asuntoByUsuarioId")
	public Set<Documento> getDocumentosForUsuarioId() {
		return this.documentosForUsuarioId;
	}

	public void setDocumentosForUsuarioId(Set<Documento> documentosForUsuarioId) {
		this.documentosForUsuarioId = documentosForUsuarioId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asuntoByAsuntoId")
	public Set<Documento> getDocumentosForAsuntoId() {
		return this.documentosForAsuntoId;
	}

	public void setDocumentosForAsuntoId(Set<Documento> documentosForAsuntoId) {
		this.documentosForAsuntoId = documentosForAsuntoId;
	}

}
