package com.ubosque.edu.co.progll.modelo;
// Generated 12/11/2018 11:20:32 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Destino generated by hbm2java
 */
@Entity
@Table(name="destino"
)
public class Destino  implements java.io.Serializable {


     private int id;
     private String nombres;
     private String apellidos;
     private String area;
     private String correo;

    public Destino() {
    }

    public Destino(int id, String nombres, String apellidos, String area, String correo) {
       this.id = id;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.area = area;
       this.correo = correo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombres", nullable=false, length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="area", nullable=false, length=45)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="correo", nullable=false)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


