package com.ubosque.edu.co.progll.modelo;
// Generated 12/11/2018 11:20:32 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento")
public class Documento implements java.io.Serializable {

	private int id;
	private Asunto asuntoByUsuarioId;
	private Asunto asuntoByAsuntoId;
	private String nombres;
	private Date fechaDocumento;
	private Date fechaRadicado;
	private String origen;
	private Long numeroRadicado;
	private String comentarios;
	private String anexo;

	public Documento() {
	}

	public Documento(int id, Asunto asuntoByUsuarioId, Asunto asuntoByAsuntoId, String nombres, String origen) {
		this.id = id;
		this.asuntoByUsuarioId = asuntoByUsuarioId;
		this.asuntoByAsuntoId = asuntoByAsuntoId;
		this.nombres = nombres;
		this.origen = origen;
	}

	public Documento(int id, Asunto asuntoByUsuarioId, Asunto asuntoByAsuntoId, String nombres, Date fechaDocumento,
			Date fechaRadicado, String origen, Long numeroRadicado, String comentarios, String anexo) {
		this.id = id;
		this.asuntoByUsuarioId = asuntoByUsuarioId;
		this.asuntoByAsuntoId = asuntoByAsuntoId;
		this.nombres = nombres;
		this.fechaDocumento = fechaDocumento;
		this.fechaRadicado = fechaRadicado;
		this.origen = origen;
		this.numeroRadicado = numeroRadicado;
		this.comentarios = comentarios;
		this.anexo = anexo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	public Asunto getAsuntoByUsuarioId() {
		return this.asuntoByUsuarioId;
	}

	public void setAsuntoByUsuarioId(Asunto asuntoByUsuarioId) {
		this.asuntoByUsuarioId = asuntoByUsuarioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "asunto_id", nullable = false)
	public Asunto getAsuntoByAsuntoId() {
		return this.asuntoByAsuntoId;
	}

	public void setAsuntoByAsuntoId(Asunto asuntoByAsuntoId) {
		this.asuntoByAsuntoId = asuntoByAsuntoId;
	}

	@Column(name = "nombres", nullable = false, length = 100)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_documento", length = 10)
	public Date getFechaDocumento() {
		return this.fechaDocumento;
	}

	public void setFechaDocumento(Date fechaDocumento) {
		this.fechaDocumento = fechaDocumento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_radicado", length = 10)
	public Date getFechaRadicado() {
		return this.fechaRadicado;
	}

	public void setFechaRadicado(Date fechaRadicado) {
		this.fechaRadicado = fechaRadicado;
	}

	@Column(name = "origen", nullable = false, length = 45)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "numero_radicado")
	public Long getNumeroRadicado() {
		return this.numeroRadicado;
	}

	public void setNumeroRadicado(Long numeroRadicado) {
		this.numeroRadicado = numeroRadicado;
	}

	@Column(name = "comentarios")
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "anexo")
	public String getAnexo() {
		return this.anexo;
	}

	public void setAnexo(String anexo) {
		this.anexo = anexo;
	}

}
