package com.ubosque.edu.co.progll.modelo;
// Generated 22/11/2018 10:18:51 AM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento")
public class Documento implements java.io.Serializable {

	private int id;
	private String titulo;
	private Date fechaDocumento;
	private Date fechaRadicado;
	private String origen;
	private int asuntoId;
	private int usuarioId;
	private Long numeroRadicado;
	private String comentarios;
	private String anexo;

	public Documento() {
	}

	public Documento(int id, String titulo, String origen, int asuntoId, int usuarioId) {
		this.id = id;
		this.titulo = titulo;
		this.origen = origen;
		this.asuntoId = asuntoId;
		this.usuarioId = usuarioId;
	}

	public Documento(int id, String titulo, Date fechaDocumento, Date fechaRadicado, String origen, int asuntoId,
			int usuarioId, Long numeroRadicado, String comentarios, String anexo) {
		this.id = id;
		this.titulo = titulo;
		this.fechaDocumento = fechaDocumento;
		this.fechaRadicado = fechaRadicado;
		this.origen = origen;
		this.asuntoId = asuntoId;
		this.usuarioId = usuarioId;
		this.numeroRadicado = numeroRadicado;
		this.comentarios = comentarios;
		this.anexo = anexo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "titulo", nullable = false, length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_documento", length = 10)
	public Date getFechaDocumento() {
		return this.fechaDocumento;
	}

	public void setFechaDocumento(Date fechaDocumento) {
		this.fechaDocumento = fechaDocumento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_radicado", length = 10)
	public Date getFechaRadicado() {
		return this.fechaRadicado;
	}

	public void setFechaRadicado(Date fechaRadicado) {
		this.fechaRadicado = fechaRadicado;
	}

	@Column(name = "origen", nullable = false, length = 45)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "asunto_id", nullable = false)
	public int getAsuntoId() {
		return this.asuntoId;
	}

	public void setAsuntoId(int asuntoId) {
		this.asuntoId = asuntoId;
	}

	@Column(name = "usuario_id", nullable = false)
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "numero_radicado")
	public Long getNumeroRadicado() {
		return this.numeroRadicado;
	}

	public void setNumeroRadicado(Long numeroRadicado) {
		this.numeroRadicado = numeroRadicado;
	}

	@Column(name = "comentarios")
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "anexo")
	public String getAnexo() {
		return this.anexo;
	}

	public void setAnexo(String anexo) {
		this.anexo = anexo;
	}

}
