package com.ubosque.edu.co.progll.modelo;
// Generated 12/11/2018 11:20:32 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "permiso")
public class Permiso implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set<RolPermiso> rolPermisos = new HashSet<RolPermiso>(0);

	public Permiso() {
	}

	public Permiso(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Permiso(int id, String nombre, Set<RolPermiso> rolPermisos) {
		this.id = id;
		this.nombre = nombre;
		this.rolPermisos = rolPermisos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permiso")
	public Set<RolPermiso> getRolPermisos() {
		return this.rolPermisos;
	}

	public void setRolPermisos(Set<RolPermiso> rolPermisos) {
		this.rolPermisos = rolPermisos;
	}

}
