package com.ubosque.edu.co.progll.modelo;
// Generated 12/11/2018 11:20:32 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolPermiso generated by hbm2java
 */
@Entity
@Table(name = "rol_permiso")
public class RolPermiso implements java.io.Serializable {

	private int id;
	private Permiso permiso;
	private Rol rol;

	public RolPermiso() {
	}

	public RolPermiso(int id, Permiso permiso, Rol rol) {
		this.id = id;
		this.permiso = permiso;
		this.rol = rol;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permiso_id", nullable = false)
	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_id", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
