package com.ubosque.edu.co.progll.modelo;
// Generated 22/11/2018 10:18:51 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RolPermiso generated by hbm2java
 */
@Entity
@Table(name = "rol_permiso")
public class RolPermiso implements java.io.Serializable {

	private int id;
	private int rolId;
	private int permisoId;

	public RolPermiso() {
	}

	public RolPermiso(int id, int rolId, int permisoId) {
		this.id = id;
		this.rolId = rolId;
		this.permisoId = permisoId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "rol_id", nullable = false)
	public int getRolId() {
		return this.rolId;
	}

	public void setRolId(int rolId) {
		this.rolId = rolId;
	}

	@Column(name = "permiso_id", nullable = false)
	public int getPermisoId() {
		return this.permisoId;
	}

	public void setPermisoId(int permisoId) {
		this.permisoId = permisoId;
	}

}
